CAP_DIR = '/opt/STITCHES_6R7.2_DISTRO-A/STITCHES_Capabilities_6R7.2_DISTRO-A'
INPUT_DIR = '/opt/STITCHES_6R7.2_DISTRO-A/STITCHES_Inputs_6R7.2_DISTRO-A'
LIB_DIR = '/opt/STITCHES_6R7.2_DISTRO-A/STITCHES_Libraries_6R7.2_DISTRO-A'
