from .ss_py import SSI_PY_TEMPLATE
from .ssi_build_sh import SSI_BUILD_SH_TEMPLATE
from .ssi_dockerfile import SSI_DOCKERFILE_TEMPLATE
from .ssi_entrypoint import SSI_ENTRYPOINT_TEMPLATE
from .ssi_main_cpp import SSI_MAIN_TEMPLATE
from .ssi_upper_cpp import SSI_UPPER_TEMPLATE
from .ssi_pybind_cpp import SSI_PYBIND_TEMPLATE
from .ssi_cmake import SSI_CMAKE_TEMPLATE
from .ssi_test_py import SSI_TEST_TEMPLATE