#!/usr/bin/env sh
set -ex

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --driver docker-container --driver-opt network=host --use
docker buildx inspect --bootstrap
