#!/usr/bin/env bash
set -ex
PROJECT_DIR="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

IMAGE_REGISTRY=${IMAGE_REGISTRY:-'localhost:5000'}
IMAGE_TAG=${IMAGE_TAG:-'latest'}

docker build -t detector-wrapper docker/detector-wrapper-amd64