#!/usr/bin/env bash
set -ex
PROJECT_DIR="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

IMAGE_REGISTRY=${IMAGE_REGISTRY:-"$HOSTNAME:5000"}
IMAGE_TAG=${IMAGE_TAG:-'dev'}
IMAGE_PLATFORMS=${IMAGE_PLATFORMS:-'linux/amd64,linux/arm64'}

docker buildx build --push --platform arm64 -t ${IMAGE_REGISTRY}/detector-wrapper-arm64:${IMAGE_TAG} docker/detector-wrapper-arm64